In [2]:
# programma da arxiv 1811.02266 fig. 3 pag.5
# il programma riconosce input che rappresentano un quadrato di 4 pixel con questa convenzione:
#  |----|----|
#  | n0 | n1 |
#  |----|----|
#  | n2 | n3 |
#  |----|----|
# dove n0,...,n3 sono i 4 bit [n0n1n2n3] corrispondenti a un valore |q1q2>. 
# L'input i e' una quaterna di valori che possono essere +1 o -1 (1 se pixel bianco, -1 se nero), e anche
# la matrice dei pesi w, cioe' il pattern da riconoscere, e' rappresentato nello stesso modo. Di entrambi l'articolo
# riporta come etichetta il numero decimale corrispondente.
# In particolare questo programma usa come matrice dei pesi 7 (cioe' [0111] = -|11>-|10>-|01>+|00>) e 
# come input 11 (cioe' [1011] = -|11>-|10>+|01>-|00>).
# quindi: pesi
#  |----|----|
#  | XX | XX |
#  |----|----|
#  | XX |    |
#  |----|----|
# input
#  |----|----|
#  | XX |    |
#  |----|----|
#  | XX | XX |
#  |----|----|

# import delle librerie 
import math
import numpy as np

# definizione dei qubit come vettori
q0 = np.array([[1],[0]])
q1 = np.array([[1],[0]])
ancilla = np.array([[1],[0]])
################ aggiungere l'ancella e modificare tutto di conseguenza ##############

# prodotto tensoriale dei 2 qubit
ini = np.kron(np.kron(q0,q1),ancilla)
print(ini)
# matrice di Hadamard 
H2 = 0.5 * np.array([[1,1,1,1],[1,-1,1,-1],[1,1,-1,-1],[1,-1,-1,1]])
H2 = np.kron(H2,np.eye(2))
print(H2)
print(H2.dot(ini))
# matrice per Z gate sul secondo qubit
Zgate = np.array([[1,0,0,0],[0,-1,0,0],[0,0,1,0],[0,0,0,-1]])  
Zgate = np.kron(Zgate,np.eye(2))
print(Zgate)
# matrice per Z gate sul primo qubit
Zgate1 = np.array([[1,0,0,0],[0,1,0,0],[0,0,-1,0],[0,0,0,-1]])  
Zgate1 = np.kron(Zgate1,np.eye(2))
print(Zgate1)
# matrice controlled Z gate
CZgate = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]])
CZgate = np.kron(CZgate,np.eye(2))
print(CZgate)
# matrice X per 2 qubit
X2 = np.array([[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]])
X2 = np.kron(X2,np.eye(2))
print(X2)
Toffoli = np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],
                    [0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
print(Toffoli)

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[ 0.5  0.   0.5  0.   0.5  0.   0.5  0. ]
 [ 0.   0.5  0.   0.5  0.   0.5  0.   0.5]
 [ 0.5  0.  -0.5 -0.   0.5  0.  -0.5 -0. ]
 [ 0.   0.5 -0.  -0.5  0.   0.5 -0.  -0.5]
 [ 0.5  0.   0.5  0.  -0.5 -0.  -0.5 -0. ]
 [ 0.   0.5  0.   0.5 -0.  -0.5 -0.  -0.5]
 [ 0.5  0.  -0.5 -0.  -0.5 -0.   0.5  0. ]
 [ 0.   0.5 -0.  -0.5 -0.  -0.5  0.   0.5]]
[[0.5]
 [0. ]
 [0.5]
 [0. ]
 [0.5]
 [0. ]
 [0.5]
 [0. ]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1. -0.  0.  0.  0.  0.]
 [ 0.  0. -0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -0.]
 [ 0.  0.  0.  0.  0.  0. -0. -1.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -0.  0.  0.]
 [ 0.  0.  0.  0. -0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -0.]
 [ 0.  0.  0.  0.  0.  0. -0. -

In [3]:
i1 = H2.dot(ini)
i2 = Zgate.dot(i1)
print(i2)
i3 = CZgate.dot(i2)
print(i3)

[[ 0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]]
[[ 0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [ 0. ]
 [ 0.5]
 [ 0. ]]


In [4]:
w1 = H2.dot(ini)
w2 = Zgate.dot(w1)
w3 = Zgate1.dot(w2)
w4 = CZgate.dot(w3)
print(w4)

[[ 0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]
 [-0.5]
 [ 0. ]]


In [6]:
iw4 = Zgate.dot(i3)
iw5 = Zgate1.dot(iw4)
iw6 = CZgate.dot(iw5)
iw7 = H2.dot(iw6)
iw8 = X2.dot(iw7)
iw9 = Toffoli.dot(iw8)
print(iw9)

[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
